export const MAX_SELECTED_KANJI = 10;
export const MAX_RANDOM_VOCAB_PER_KANJI = 3;
export const QUIZ_QUESTION_COUNT = 10;

export const QUIZ_MODELS = [
  { value: 'claude-sonnet-4-6', labelKey: 'modelSonnetLabel' },
  { value: 'claude-opus-4-7', labelKey: 'modelOpusLabel' },
  { value: 'claude-haiku-4-5-20251001', labelKey: 'modelHaikuLabel' },
];

export const DEFAULT_QUIZ_MODEL = 'claude-sonnet-4-6';

export const SRS_INTERVALS_DAYS = [0, 1, 3, 7, 14, 30];

export const VOCAB_LOADERS = {
  id: {
    n5: () => import('../Data/Vocabulary/Indonesian/n5_vocab_cleaned.csv?raw'),
    n4: () => import('../Data/Vocabulary/Indonesian/n4_vocab_cleaned.csv?raw'),
    n3: () => import('../Data/Vocabulary/Indonesian/n3_vocab_cleaned.csv?raw'),
    n2: () => import('../Data/Vocabulary/Indonesian/n2_vocab_cleaned.csv?raw'),
    n1: () => import('../Data/Vocabulary/Indonesian/n1_vocab_cleaned.csv?raw'),
  },
  en: {
    n5: () => import('../Data/Vocabulary/English/n5_vocab_cleaned.csv?raw'),
    n4: () => import('../Data/Vocabulary/English/n4_vocab_cleaned.csv?raw'),
    n3: () => import('../Data/Vocabulary/English/n3_vocab_cleaned.csv?raw'),
    n2: () => import('../Data/Vocabulary/English/n2_vocab_cleaned.csv?raw'),
    n1: () => import('../Data/Vocabulary/English/n1_vocab_cleaned.csv?raw'),
  },
};

export const LEVELS = [
  {
    value: 5,
    label: 'N5',
    loadKanji: () => import('../Data/Kanji/kanji_n5.json'),
    loadVocab: (language) => (VOCAB_LOADERS[language] || VOCAB_LOADERS.id).n5(),
  },
  {
    value: 4,
    label: 'N4',
    loadKanji: () => import('../Data/Kanji/kanji_n4.json'),
    loadVocab: (language) => (VOCAB_LOADERS[language] || VOCAB_LOADERS.id).n4(),
  },
  {
    value: 3,
    label: 'N3',
    loadKanji: () => import('../Data/Kanji/kanji_n3.json'),
    loadVocab: (language) => (VOCAB_LOADERS[language] || VOCAB_LOADERS.id).n3(),
  },
  {
    value: 2,
    label: 'N2',
    loadKanji: () => import('../Data/Kanji/kanji_n2.json'),
    loadVocab: (language) => (VOCAB_LOADERS[language] || VOCAB_LOADERS.id).n2(),
  },
  {
    value: 1,
    label: 'N1',
    loadKanji: () => import('../Data/Kanji/kanji_n1.json'),
    loadVocab: (language) => (VOCAB_LOADERS[language] || VOCAB_LOADERS.id).n1(),
  },
];

export const LANGUAGES = [
  { value: 'id', label: 'Indonesia' },
  { value: 'en', label: 'English' },
  { value: 'ja', label: '日本語' },
  { value: 'ko', label: '한국어' },
  { value: 'es', label: 'Español' },
];

export const SUPPORTED_LANGUAGES = LANGUAGES.filter(
  (item) => item.value === 'id' || item.value === 'en',
);

export const LEVEL_BY_VALUE = Object.fromEntries(
  LEVELS.map((level) => [level.value, level]),
);

export const LEVEL_LABEL_BY_VALUE = Object.fromEntries(
  LEVELS.map((level) => [level.value, level.label]),
);

export const TEXT = {
  id: {
    appName: 'Kanji Study',
    title: 'Generator Soal Kanji JLPT',
    subtitle: 'Pilih kanji, ambil vocabulary, lalu buat latihan membaca yang fokus.',
    language: 'Bahasa',
    picked: 'dipilih',
    levelTitle: 'Pilih level',
    allLevels: 'semua level',
    searchLabel: 'Cari kanji',
    searchPlaceholder: 'kanji, arti, atau reading',
    random: 'Acak 10',
    reset: 'Kosongkan',
    openVocabPicker: 'Racik vocab',
    vocabPickerTitle: 'Racik vocab random',
    vocabPickerSubtitle: 'Pilih preferensi level vocab, lalu sistem mengambil maksimal 3 kata untuk tiap kanji.',
    preferredVocabLevel: 'Prefer vocab',
    allVocabLevels: 'Tidak pilih level berarti semua vocab boleh masuk.',
    preferredHint: 'Prioritas: {levels}',
    generateVocab: 'Ambil vocab random',
    regenerateVocab: 'Acak ulang vocab',
    generateQuiz: 'Generate 10 soal',
    generatingQuiz: 'Membuat soal...',
    quizSectionTitle: 'Soal bacaan kanji',
    quizError: 'Gagal membuat soal. Cek API server dan env ANTHROPIC_API_KEY.',
    quizErrorNoServer: 'Server API tidak bisa dijangkau. Pastikan server sudah dijalankan dengan "npm run api".',
    quizErrorNoApiKey: 'ANTHROPIC_API_KEY belum dikonfigurasi. Tambahkan ke file .env di folder server.',
    quizErrorRateLimit: 'Terlalu banyak permintaan ke API. Tunggu sebentar lalu coba lagi.',
    correctAnswer: 'Jawaban benar',
    sentenceVocab: 'Vocab di kalimat',
    wordTranslation: 'Terjemahan kata',
    sentenceTranslation: 'Terjemahan kalimat',
    answerExplanationWithTranslation: '"{vocab}" dibaca "{reading}". Arti: {translation}.',
    answerExplanationNoTranslation: '"{vocab}" dibaca "{reading}".',
    close: 'Tutup',
    noRandomYet: 'Pilih preferensi, lalu ambil vocab random.',
    selectedKanjiLabel: 'Kanji pilihan',
    viewVocab: 'Lihat vocab',
    vocabPreviewTitle: 'Vocab untuk {kanji}',
    vocabPreviewSubtitle: 'Semua vocab yang memuat kanji ini, lengkap dengan bunyinya.',
    soundLabel: 'Bunyi',
    shelfTitle: 'List kanji',
    deckTitle: 'Dek latihan',
    imageCaption: 'Satu dek kecil, satu sesi fokus.',
    loadingKanji: 'Membuka kartu {level}...',
    loadingVocab: 'Mencari kosakata...',
    available: '{count} kartu tersedia di {level}.',
    emptyDeck: 'Klik kartu kanji untuk mulai meracik dek.',
    deckStats: '{kanji}/10 kanji dipilih',
    strokes: 'goresan',
    fallbackMeaning: 'kanji',
    loadingCards: 'Kartu sedang dibuka.',
    vocabLoadingInline: 'Kosakata sedang dicari.',
    vocabCount: '{count} kosakata',
    noVocab: 'Belum ada kosakata untuk kartu ini.',
    ready: 'Siap diracik.',
    kanjiError: 'Data kanji {level} belum berhasil dimuat.',
    vocabError: 'Data kosakata belum berhasil dimuat.',
    documentTitle: 'Generator Soal Kanji JLPT',
    flashcardMode: 'Mode Flashcard',
    flashcardFlip: 'Klik untuk balik',
    flashcardGotIt: 'Paham',
    flashcardPractice: 'Latih lagi',
    flashcardClose: 'Keluar Flashcard',
    flashcardCount: '{current} / {total}',
    flashcardFront: 'Tebak artinya',
    flashcardBack: 'Jawaban',
    flashcardDone: 'Sesi selesai!',
    flashcardRestart: 'Ulangi',
    progressTitle: 'Progres Kanji',
    masteredLabel: 'Dikuasai',
    weakLabel: 'Lemah',
    reviewDue: 'Perlu review',
    progressStats: '{mastered} dikuasai · {weak} lemah · {due} perlu review',
    keyboardHint: 'Tekan 1–4 atau A–D untuk memilih · Enter untuk lanjut',
    onReadings: 'On',
    kunReadings: 'Kun',
    reviewWrongOnly: 'Ulangi yang salah ({count})',
    reviewAllCorrect: 'Semua jawaban benar!',
    quizFromCache: 'Hasil dari cache lokal',
    quizCacheCleared: 'Cache quiz dihapus',
    clearQuizCache: 'Hapus cache quiz',
    strokeOrder: 'Urutan goresan',
    strokeOrderTitle: 'Urutan goresan {kanji}',
    strokeOrderLoading: 'Memuat urutan goresan...',
    strokeOrderError: 'Tidak tersedia di KanjiVG.',
    strokeOrderPlay: 'Putar animasi',
    strokeOrderPause: 'Jeda',
    strokeOrderReplay: 'Ulang',
    statsButton: 'Statistik',
    statsTitle: 'Statistik Belajar',
    statsTotalKanji: 'Total kanji dipelajari',
    statsByLevel: 'Per level JLPT',
    statsAccuracy: 'Akurasi quiz',
    statsAccuracyAll: '{correct}/{total} ({percent}%)',
    statsStreak: 'Streak harian',
    statsStreakDays: '{count} hari',
    statsLastSession: 'Sesi terakhir',
    statsNoData: 'Belum ada data. Mulai quiz untuk tracking statistik.',
    statsReset: 'Reset semua progress',
    statsResetConfirm: 'Yakin ingin menghapus semua progress dan statistik?',
    statsExport: 'Export progress',
    statsImport: 'Import progress',
    statsImportConfirm: 'Ganti progress yang ada sekarang? Tindakan ini tidak bisa dibatalkan.',
    statsImportError: 'File tidak valid. Pastikan ini hasil export progress.',
    appInstall: 'Pasang aplikasi',
    appUpdate: 'Versi baru tersedia. Reload?',
    heisigLabel: 'Heisig',
    breakdown: 'Breakdown',
    breakdownLabel: 'Komponen',
    breakdownTitle: 'Komponen {kanji}',
    breakdownSubtitle: 'Bagian-bagian yang menyusun kanji ini, diambil dari KanjiVG.',
    breakdownLoading: 'Mengambil komponen...',
    breakdownError: 'Data komponen tidak tersedia.',
    breakdownEmpty: 'Kanji ini tidak punya komponen turunan di KanjiVG.',
    breakdownRadicalTag: 'radikal',
    playAudio: 'Dengar bunyi',
    audioUnsupported: 'Browser tidak mendukung audio Jepang',
    sortLabel: 'Urutkan',
    sortDefault: 'Default',
    sortFreq: 'Paling sering',
    sortGrade: 'Per grade',
    gradeBadge: 'Grade {grade}',
    freqBadge: 'Freq #{freq}',
    modelLabel: 'Model',
    modelHint: 'Pilih model akan tersimpan dan dipakai lagi nanti.',
    modelSonnetLabel: 'Sonnet 4.6 — Balanced',
    modelOpusLabel: 'Opus 4.7 — Best quality',
    modelHaikuLabel: 'Haiku 4.5 — Fastest',
  },
  en: {
    appName: 'Kanji Study',
    title: 'JLPT Kanji Question Generator',
    subtitle: 'Pick kanji, draw vocabulary, and generate focused reading practice.',
    language: 'Language',
    picked: 'picked',
    levelTitle: 'Choose level',
    allLevels: 'all levels',
    searchLabel: 'Find kanji',
    searchPlaceholder: 'kanji, meaning, or reading',
    random: 'Shuffle 10',
    reset: 'Clear',
    openVocabPicker: 'Pick vocab',
    vocabPickerTitle: 'Random vocab draw',
    vocabPickerSubtitle: 'Choose preferred vocab levels, then draw up to 3 words for each kanji.',
    preferredVocabLevel: 'Vocab preference',
    allVocabLevels: 'No level selected means every vocab level can appear.',
    preferredHint: 'Priority: {levels}',
    generateVocab: 'Draw random vocab',
    regenerateVocab: 'Shuffle vocab again',
    generateQuiz: 'Generate 10 questions',
    generatingQuiz: 'Generating quiz...',
    quizSectionTitle: 'Kanji reading quiz',
    quizError: 'Could not generate quiz. Check the API server and ANTHROPIC_API_KEY env.',
    quizErrorNoServer: 'API server is unreachable. Make sure the server is running with "npm run api".',
    quizErrorNoApiKey: 'ANTHROPIC_API_KEY is not configured. Add it to the .env file in the server folder.',
    quizErrorRateLimit: 'Too many API requests. Wait a moment and try again.',
    correctAnswer: 'Correct answer',
    sentenceVocab: 'Words in sentence',
    wordTranslation: 'Word meaning',
    sentenceTranslation: 'Sentence meaning',
    answerExplanationWithTranslation: '"{vocab}" is read as "{reading}". Meaning: {translation}.',
    answerExplanationNoTranslation: '"{vocab}" is read as "{reading}".',
    close: 'Close',
    noRandomYet: 'Choose preferences, then draw random vocab.',
    selectedKanjiLabel: 'Selected kanji',
    viewVocab: 'View vocab',
    vocabPreviewTitle: 'Vocab for {kanji}',
    vocabPreviewSubtitle: 'Every word that contains this kanji, with its reading.',
    soundLabel: 'Sound',
    shelfTitle: 'Kanji list',
    deckTitle: 'Practice deck',
    imageCaption: 'One small deck, one focused session.',
    loadingKanji: 'Opening {level} cards...',
    loadingVocab: 'Finding vocabulary...',
    available: '{count} cards ready in {level}.',
    emptyDeck: 'Click kanji cards to start your deck.',
    deckStats: '{kanji}/10 kanji picked',
    strokes: 'strokes',
    fallbackMeaning: 'kanji',
    loadingCards: 'Cards are opening.',
    vocabLoadingInline: 'Finding vocabulary.',
    vocabCount: '{count} words',
    noVocab: 'No vocabulary found for this card yet.',
    ready: 'Ready to draw.',
    kanjiError: '{level} kanji could not be loaded.',
    vocabError: 'Vocabulary could not be loaded.',
    documentTitle: 'JLPT Kanji Question Generator',
    flashcardMode: 'Flashcard Mode',
    flashcardFlip: 'Click to flip',
    flashcardGotIt: 'Got it',
    flashcardPractice: 'Practice more',
    flashcardClose: 'Exit Flashcards',
    flashcardCount: '{current} / {total}',
    flashcardFront: 'Guess the meaning',
    flashcardBack: 'Answer',
    flashcardDone: 'Session complete!',
    flashcardRestart: 'Restart',
    progressTitle: 'Kanji Progress',
    masteredLabel: 'Mastered',
    weakLabel: 'Weak',
    reviewDue: 'Review due',
    progressStats: '{mastered} mastered · {weak} weak · {due} due for review',
    keyboardHint: 'Press 1–4 or A–D to pick · Enter to continue',
    onReadings: 'On',
    kunReadings: 'Kun',
    reviewWrongOnly: 'Review wrong only ({count})',
    reviewAllCorrect: 'All answers correct!',
    quizFromCache: 'From local cache',
    quizCacheCleared: 'Quiz cache cleared',
    clearQuizCache: 'Clear quiz cache',
    strokeOrder: 'Stroke order',
    strokeOrderTitle: 'Stroke order for {kanji}',
    strokeOrderLoading: 'Loading stroke order...',
    strokeOrderError: 'Not available in KanjiVG.',
    strokeOrderPlay: 'Play animation',
    strokeOrderPause: 'Pause',
    strokeOrderReplay: 'Replay',
    statsButton: 'Stats',
    statsTitle: 'Study Statistics',
    statsTotalKanji: 'Total kanji studied',
    statsByLevel: 'By JLPT level',
    statsAccuracy: 'Quiz accuracy',
    statsAccuracyAll: '{correct}/{total} ({percent}%)',
    statsStreak: 'Daily streak',
    statsStreakDays: '{count} days',
    statsLastSession: 'Last session',
    statsNoData: 'No data yet. Start a quiz to track statistics.',
    statsReset: 'Reset all progress',
    statsResetConfirm: 'Are you sure you want to delete all progress and stats?',
    statsExport: 'Export progress',
    statsImport: 'Import progress',
    statsImportConfirm: 'Replace your current progress? This cannot be undone.',
    statsImportError: 'Invalid file. Make sure it is a progress export.',
    appInstall: 'Install app',
    appUpdate: 'New version available. Reload?',
    heisigLabel: 'Heisig',
    breakdown: 'Breakdown',
    breakdownLabel: 'Components',
    breakdownTitle: 'Components of {kanji}',
    breakdownSubtitle: 'The building blocks of this kanji, sourced from KanjiVG.',
    breakdownLoading: 'Fetching components...',
    breakdownError: 'Component data not available.',
    breakdownEmpty: 'KanjiVG lists no sub-components for this kanji.',
    breakdownRadicalTag: 'radical',
    playAudio: 'Play audio',
    audioUnsupported: 'Browser does not support Japanese audio',
    sortLabel: 'Sort',
    sortDefault: 'Default',
    sortFreq: 'Most frequent',
    sortGrade: 'By grade',
    gradeBadge: 'Grade {grade}',
    freqBadge: 'Freq #{freq}',
    modelLabel: 'Model',
    modelHint: 'Your model choice is saved for next time.',
    modelSonnetLabel: 'Sonnet 4.6 — Balanced',
    modelOpusLabel: 'Opus 4.7 — Best quality',
    modelHaikuLabel: 'Haiku 4.5 — Fastest',
  },
  ja: {
    appName: '',
    title: 'JLPTデッキを作ろう',
    subtitle: '漢字を1-10個選び、ポップアップで語彙をランダムに選びます。',
    language: '言語',
    picked: '選択中',
    levelTitle: 'レベル',
    allLevels: 'すべてのレベル',
    searchLabel: 'カード検索',
    searchPlaceholder: '漢字、意味、読み',
    random: '10枚シャッフル',
    reset: 'クリア',
    openVocabPicker: '語彙を選ぶ',
    vocabPickerTitle: 'ランダム語彙',
    vocabPickerSubtitle: '語彙レベルを選び、各漢字に最大3つの語彙を入れます。',
    preferredVocabLevel: '語彙レベル',
    allVocabLevels: 'レベル未選択なら、すべての語彙が対象です。',
    preferredHint: '優先: {levels}',
    generateVocab: 'ランダム選択',
    regenerateVocab: 'もう一度選ぶ',
    generateQuiz: '10問を作る',
    generatingQuiz: '問題を作成中...',
    quizSectionTitle: '漢字読みクイズ',
    quizError: '問題を作れませんでした。APIサーバーとANTHROPIC_API_KEYを確認してください。',
    quizErrorNoServer: 'APIサーバーに接続できません。"npm run api"でサーバーを起動してください。',
    quizErrorNoApiKey: 'ANTHROPIC_API_KEYが設定されていません。サーバーの.envファイルに追加してください。',
    quizErrorRateLimit: 'APIリクエストが多すぎます。少し待ってからもう一度お試しください。',
    correctAnswer: '正解',
    sentenceVocab: '文の言葉',
    wordTranslation: '言葉の意味',
    sentenceTranslation: '文の意味',
    answerExplanationWithTranslation: '「{vocab}」の読み方は「{reading}」です。意味: {translation}。',
    answerExplanationNoTranslation: '「{vocab}」の読み方は「{reading}」です。',
    close: '閉じる',
    noRandomYet: '好みを選んで、語彙をランダム選択しましょう。',
    selectedKanjiLabel: '選択した漢字',
    viewVocab: '語彙を見る',
    vocabPreviewTitle: '{kanji}の語彙',
    vocabPreviewSubtitle: 'この漢字を含む語彙と読みです。',
    soundLabel: '読み',
    shelfTitle: '漢字の棚',
    deckTitle: '練習デッキ',
    imageCaption: '小さなデッキで、集中した一回を。',
    loadingKanji: '{level}のカードを開いています...',
    loadingVocab: '語彙を探しています...',
    available: '{level}に{count}枚あります。',
    emptyDeck: '漢字カードを選んでデッキを作りましょう。',
    deckStats: '漢字{kanji}/10個',
    strokes: '画',
    fallbackMeaning: '漢字',
    loadingCards: 'カードを準備しています。',
    vocabLoadingInline: '語彙を探しています。',
    vocabCount: '語彙{count}個',
    noVocab: 'このカードの語彙はまだありません。',
    ready: '語彙を選べます。',
    kanjiError: '{level}の漢字データを読み込めませんでした。',
    vocabError: '語彙データを読み込めませんでした。',
    documentTitle: 'JLPT kanji specifik question generator',
    flashcardMode: 'フラッシュカード',
    flashcardFlip: 'クリックで裏返す',
    flashcardGotIt: '覚えた',
    flashcardPractice: 'もっと練習',
    flashcardClose: '終了',
    flashcardCount: '{current} / {total}',
    flashcardFront: '意味を答えよ',
    flashcardBack: '答え',
    flashcardDone: 'セッション完了！',
    flashcardRestart: 'もう一度',
    progressTitle: '漢字の進捗',
    masteredLabel: '習得済み',
    weakLabel: '要練習',
    reviewDue: '復習が必要',
    progressStats: '{mastered}習得 · {weak}要練習 · {due}復習待ち',
    keyboardHint: '1〜4またはA〜Dで選択 · Enterで次へ',
    onReadings: '音',
    kunReadings: '訓',
  },
  ko: {
    appName: '',
    title: 'JLPT 덱 만들기',
    subtitle: '한자 1-10개를 고르고 팝업에서 어휘를 랜덤으로 뽑아요.',
    language: '언어',
    picked: '선택',
    levelTitle: '레벨',
    allLevels: '모든 레벨',
    searchLabel: '카드 찾기',
    searchPlaceholder: '한자, 뜻, 읽기',
    random: '10개 랜덤',
    reset: '비우기',
    openVocabPicker: '어휘 뽑기',
    vocabPickerTitle: '랜덤 어휘 뽑기',
    vocabPickerSubtitle: '선호 어휘 레벨을 고르면 한자마다 최대 3개를 뽑아요.',
    preferredVocabLevel: '어휘 선호',
    allVocabLevels: '레벨을 고르지 않으면 모든 어휘가 나올 수 있어요.',
    preferredHint: '우선: {levels}',
    generateVocab: '랜덤 어휘 뽑기',
    regenerateVocab: '다시 뽑기',
    generateQuiz: '10문제 만들기',
    generatingQuiz: '문제를 만드는 중...',
    quizSectionTitle: '한자 읽기 문제',
    quizError: '문제를 만들 수 없어요. API 서버와 ANTHROPIC_API_KEY를 확인해 주세요.',
    quizErrorNoServer: 'API 서버에 연결할 수 없어요. "npm run api"로 서버를 실행해 주세요.',
    quizErrorNoApiKey: 'ANTHROPIC_API_KEY가 설정되지 않았어요. 서버 .env 파일에 추가해 주세요.',
    quizErrorRateLimit: 'API 요청이 너무 많아요. 잠시 후 다시 시도해 주세요.',
    correctAnswer: '정답',
    sentenceVocab: '문장 속 단어',
    wordTranslation: '단어 뜻',
    sentenceTranslation: '문장 뜻',
    answerExplanationWithTranslation: '"{vocab}"의 읽기는 "{reading}"입니다. 뜻: {translation}.',
    answerExplanationNoTranslation: '"{vocab}"의 읽기는 "{reading}"입니다.',
    close: '닫기',
    noRandomYet: '선호를 고른 뒤 랜덤 어휘를 뽑아 보세요.',
    selectedKanjiLabel: '선택한 한자',
    viewVocab: '어휘 보기',
    vocabPreviewTitle: '{kanji} 어휘',
    vocabPreviewSubtitle: '이 한자가 들어간 어휘와 읽기입니다.',
    soundLabel: '읽기',
    shelfTitle: '한자 선반',
    deckTitle: '연습 덱',
    imageCaption: '작은 덱 하나, 집중 한 번.',
    loadingKanji: '{level} 카드를 여는 중...',
    loadingVocab: '어휘를 찾는 중...',
    available: '{level}에 카드 {count}개.',
    emptyDeck: '한자 카드를 눌러 덱을 만들어 보세요.',
    deckStats: '한자 {kanji}/10개 선택',
    strokes: '획',
    fallbackMeaning: '한자',
    loadingCards: '카드를 준비하고 있어요.',
    vocabLoadingInline: '어휘를 찾고 있어요.',
    vocabCount: '어휘 {count}개',
    noVocab: '이 카드에는 아직 어휘가 없어요.',
    ready: '어휘를 뽑을 수 있어요.',
    kanjiError: '{level} 한자 데이터를 불러오지 못했어요.',
    vocabError: '어휘 데이터를 불러오지 못했어요.',
    documentTitle: 'JLPT kanji specifik question generator',
    flashcardMode: '플래시카드',
    flashcardFlip: '클릭하여 뒤집기',
    flashcardGotIt: '알겠어요',
    flashcardPractice: '더 연습하기',
    flashcardClose: '종료',
    flashcardCount: '{current} / {total}',
    flashcardFront: '뜻을 맞춰보세요',
    flashcardBack: '정답',
    flashcardDone: '세션 완료!',
    flashcardRestart: '다시 시작',
    progressTitle: '한자 진행 상황',
    masteredLabel: '습득',
    weakLabel: '약함',
    reviewDue: '복습 필요',
    progressStats: '{mastered} 습득 · {weak} 약함 · {due} 복습 대기',
    keyboardHint: '1~4 또는 A~D로 선택 · Enter로 다음',
    onReadings: '음독',
    kunReadings: '훈독',
  },
  es: {
    appName: '',
    title: 'Arma tu mazo JLPT',
    subtitle: 'Elige 1-10 kanji y deja que el pop-up elija vocabulario al azar.',
    language: 'Idioma',
    picked: 'elegidos',
    levelTitle: 'Nivel',
    allLevels: 'todos los niveles',
    searchLabel: 'Buscar cartas',
    searchPlaceholder: 'kanji, significado o lectura',
    random: 'Mezclar 10',
    reset: 'Limpiar',
    openVocabPicker: 'Elegir vocab',
    vocabPickerTitle: 'Vocabulario al azar',
    vocabPickerSubtitle: 'Elige niveles preferidos y toma hasta 3 palabras por kanji.',
    preferredVocabLevel: 'Preferencia vocab',
    allVocabLevels: 'Sin nivel seleccionado, puede aparecer cualquier vocabulario.',
    preferredHint: 'Prioridad: {levels}',
    generateVocab: 'Tomar vocab al azar',
    regenerateVocab: 'Mezclar otra vez',
    generateQuiz: 'Generar 10 preguntas',
    generatingQuiz: 'Generando preguntas...',
    quizSectionTitle: 'Preguntas de lectura kanji',
    quizError: 'No se pudieron generar preguntas. Revisa el servidor API y ANTHROPIC_API_KEY.',
    quizErrorNoServer: 'El servidor API no responde. Asegúrate de ejecutarlo con "npm run api".',
    quizErrorNoApiKey: 'ANTHROPIC_API_KEY no está configurado. Agrégalo al archivo .env del servidor.',
    quizErrorRateLimit: 'Demasiadas solicitudes a la API. Espera un momento e intenta de nuevo.',
    correctAnswer: 'Respuesta correcta',
    sentenceVocab: 'Palabras en la frase',
    wordTranslation: 'Significado',
    sentenceTranslation: 'Significado de la frase',
    answerExplanationWithTranslation: '"{vocab}" se lee "{reading}". Traduccion: {translation}.',
    answerExplanationNoTranslation: '"{vocab}" se lee "{reading}".',
    close: 'Cerrar',
    noRandomYet: 'Elige preferencias y toma vocabulario al azar.',
    selectedKanjiLabel: 'Kanji elegidos',
    viewVocab: 'Ver vocab',
    vocabPreviewTitle: 'Vocabulario de {kanji}',
    vocabPreviewSubtitle: 'Todas las palabras que contienen este kanji, con su lectura.',
    soundLabel: 'Lectura',
    shelfTitle: 'Estante kanji',
    deckTitle: 'Mazo de práctica',
    imageCaption: 'Un mazo pequeño, una sesión enfocada.',
    loadingKanji: 'Abriendo cartas {level}...',
    loadingVocab: 'Buscando vocabulario...',
    available: '{count} cartas listas en {level}.',
    emptyDeck: 'Toca cartas kanji para empezar tu mazo.',
    deckStats: '{kanji}/10 kanji elegidos',
    strokes: 'trazos',
    fallbackMeaning: 'kanji',
    loadingCards: 'Preparando cartas.',
    vocabLoadingInline: 'Buscando vocabulario.',
    vocabCount: '{count} palabras',
    noVocab: 'Aún no hay vocabulario para esta carta.',
    ready: 'Listo para elegir vocab.',
    kanjiError: 'No se pudieron cargar los kanji {level}.',
    vocabError: 'No se pudo cargar el vocabulario.',
    documentTitle: 'JLPT kanji specifik question generator',
    flashcardMode: 'Modo Flashcard',
    flashcardFlip: 'Clic para voltear',
    flashcardGotIt: 'Lo sé',
    flashcardPractice: 'Practicar más',
    flashcardClose: 'Salir',
    flashcardCount: '{current} / {total}',
    flashcardFront: 'Adivina el significado',
    flashcardBack: 'Respuesta',
    flashcardDone: '¡Sesión completada!',
    flashcardRestart: 'Reiniciar',
    progressTitle: 'Progreso Kanji',
    masteredLabel: 'Dominado',
    weakLabel: 'Débil',
    reviewDue: 'Revisión pendiente',
    progressStats: '{mastered} dominados · {weak} débiles · {due} pendientes',
    keyboardHint: 'Presiona 1–4 o A–D para elegir · Enter para continuar',
    onReadings: 'On',
    kunReadings: 'Kun',
  },
};
